name: Tic_tac_toe

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libsfml-dev

      - name: Compile project
       run: g++ -o Tic_tac_toe src/main.cpp src/player.h src/gamelogic.h src/bouton.h -I. -lsfml-graphics -lsfml-window -lsfml-system
      - name: Run the game (optional, for testing)
        run: ./Tic_tac_toe || echo "Execution skipped in CI environment"
