name: CI (Testing Branch)

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" , "realization" , "testing" ] 

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Always Pass
        run: echo "✅ CI check passed "
