name: CI 

on:
  push:
    branches: [ "**" ]  
  pull_request:
    branches: [ "**" ] 

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Always Pass
        run: echo "✅ CI check passed"
